title: brad makes maps
description: brad makes maps is a portfolio of my cartography work, a link to my Python github repository, and other interests
show_downloads: true
google_analytics:
theme: jekyll-theme-architect